### ISSUE TITLE
由于文件拷贝出错导致编译出错

### ISSUE THREAD

**Issue by welann** [Chaf-Libraries/Ilum#5]
在plugin.lua中的
```
after_build(function (target)
        //这里
        local source_path = path.join("$(projectdir)", target:targetdir(), string.format("%s.dll", target:name()))
        
```
在我的电脑上（win11）会造成错误的拼接，生成一个错误的位置：
![image](https://user-images.githubusercontent.com/49773825/220413604-b65b2517-7ebd-4913-a5bc-e6087b7b29cb.png)
在删除$(projectdir)后可以正常编译运行（大概？

另外问下仓库里面没有提供模型文件吗？我看着那个import按钮不知道要导入哪些东西

**Comment by Chaphlagical** [comment]
感谢指正！在我电脑上没问题就没注意，把`$(projectdir)`删了应该是可以的

导入的话目前用的是assimp导入模型和stb导入图片，模型主要支持obj、fbx、ply、gltf/glb，图片支持hdr、png、jpg、bmp、dds(dds可能有bug)

资源的话，gltf支持相对较好，推荐在gltf官方仓库下载[https://github.com/KhronosGroup/glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models)
hdr图片默认认为是等距柱状投影图，会自动转成TextureCube

具体操作可以看我b站发的视频[https://www.bilibili.com/video/BV1Zy4y1f7PX](https://www.bilibili.com/video/BV1Zy4y1f7PX)
